name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/sitewatcher
  TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/sitewatcher_test
  JWT_SECRET: test-secret-key-for-ci-only-min-32-chars
  WORKER_BASE_URL: https://your-worker.workers.dev

jobs:
  api-build:
    name: API Build Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd apps/api
          pip install -e ".[dev]"

      - name: Check imports
        run: |
          cd apps/api
          python -c "from app.main import app; print('✅ API imports successfully')"

  web-build:
    name: Web Build Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build shared package
        run: |
          cd packages/shared
          npm run build

      - name: Build web
        run: |
          cd apps/web
          npm run build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000

  all-checks-passed:
    name: All Checks Passed
    needs:
      - api-build
      - web-build
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "✅ Build checks passed! Ready for deployment."
